services:
  - type: web
    name: rcb-ticket-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 8 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
      - key: RCB_URL_1
        value: https://rcb.iplt20.com/
      - key: RCB_URL_2
        value: https://rcb.iplt20.com/matches
